### ISSUE TITLE
Mapped instance expected for relationship comparison to object

### ISSUE THREAD

**Issue by dehy** [briancappello/py-yaml-fixtures#9]
First of all, thank you for your work. I'm relatively new to the Python world. Coming from PHP, the [nelmio/alice](https://github.com/nelmio/alice) library is a no-brainer and I'm very happy to have found this lib you made 👍

I'm using SQLAlchemy 2.0.7 and cannot get this library to work on Many-to-Many relationship for a "Mapped instance expected" reason.
I'm using `Flask-SQLAlchemy` v3.0.3 but I'm using the Standalone SQLAlchemy procedure for better control in my workflow.

I cannot understand what I did wrong, or if it's a bug. 🤷‍♂️

**The error**
```
sqlalchemy.exc.ArgumentError: Mapped instance expected for relationship comparison to object.   Classes, queries and other SQL elements are not accepted in this context; for comparison with a subquery, use UserRoleAssociation.user.has(**criteria)
```

**The models**
```python
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import ForeignKey, String
from sqlalchemy.ext.associationproxy import association_proxy, AssociationProxy
from sqlalchemy.orm import relationship, mapped_column, Mapped

[...]
db = SQLAlchemy(app) # then db.Model inherits DeclarativeBase

class UserRoleAssociation(db.Model):
    """Join table between Role and User"""

    __tablename__ = "users_roles"

    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), primary_key=True, nullable=False)
    user: Mapped["User"] = relationship(back_populates="user_role_associations")

    role_id: Mapped[int] = mapped_column(ForeignKey("roles.id"), primary_key=True, nullable=False)
    role: Mapped["Role"] = relationship(back_populates="role_user_associations")

    def __init__(self, user=None, role=None):
        self.user = user
        self.role = role


class Role(db.Model):
    __tablename__ = "roles"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(50), unique=True)

    role_user_associations: Mapped[List["UserRoleAssociation"]] = relationship(back_populates="role")
    users: AssociationProxy[List["User"]] = association_proxy("role_user_associations", "user", creator=lambda u: UserRoleAssociation(user=u))


class User(db.Model):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(64), index=True, unique=True)

    user_role_associations: Mapped[List["UserRoleAssociation"]] = relationship(back_populates="user")
    roles: AssociationProxy[List["Role"]] = association_proxy("user_role_associations", "role", creator=lambda r: UserRoleAssociation(role=r))
```

**The fixtures**

User.yaml
```yaml
user_admin:
  name: admin
```

Role.yaml
```yaml
role_admin:
  name: Admin
```

UserRoleAssociation.yaml
```yaml
user_admin_role_admin:
  user: User(user_admin)
  role: Role(role_admin)
```

**The called code**
```python
    model_classes = [User, Role, UserRoleAssociation]
    factory = SQLAlchemyModelFactory(db.session, model_classes)
    loader = FixturesLoader(factory, fixture_dirs=['fixtures'])

    loader.create_all(lambda identifier, model, created: print(
        '{action} {identifier}: {model}'.format(
            action='Creating' if created else 'Updating',
            identifier=identifier.key,
            model=repr(model)
    )))
```

**The stacktrace**
```python
Traceback (most recent call last):
  File "/srv/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/srv/venv/lib/python3.10/site-packages/flask/cli.py", line 1050, in main
    cli.main()
  File "/srv/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/srv/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/srv/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/venv/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/srv/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/srv/project/frontend/fixtures.py", line 77, in load
    loader.create_all(lambda identifier, model, created: print(
  File "/srv/venv/src/py-yaml-fixtures/py_yaml_fixtures/fixtures_loader.py", line 98, in create_all
    model_instance, created = self.factory.create_or_update(identifier, data)
  File "/srv/venv/src/py-yaml-fixtures/py_yaml_fixtures/factories/sqlalchemy.py", line 41, in create_or_update
    instance = self._get_existing(identifier, data)
  File "/srv/venv/src/py-yaml-fixtures/py_yaml_fixtures/factories/sqlalchemy.py", line 79, in _get_existing
    filter_expressions.append(getattr(model_class, k) == v)
  File "/srv/venv/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 539, in __eq__
    return self.operate(eq, other)
  File "/srv/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 444, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[return-value]  # noqa: E501
  File "/srv/venv/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 753, in __eq__
    self.property._optimized_compare(
  File "/srv/venv/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 1177, in _optimized_compare
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapped instance expected for relationship comparison to object.   Classes, queries and other SQL elements are not accepted in this context; for comparison with a subquery, use UserRoleAssociation.user.has(**criteria).
```

**Comment by briancappello** [comment]
Hi @dehy, let me take a look after work and get back to you - I haven't tested this with SQLAlchemy 2.x yet so there very well may be bugs :/

**Comment by briancappello** [comment]
Hey @dehy apologies for the delay - I have pushed a commit to master which in my testing of your posted code fixes this bug with SQLAlchemy 2.x (thank you for the thorough report!!!). 

Can you test it out and verify if it's working for you, or if you hit any other bugs? Something like this aught to work:

```
cd ~/dev  # or wherever, just an example dir for reference
git clone git@github.com:briancappello/py-yaml-fixtures.git

# activate your virtualenv
pip install -e ~/dev/py-yaml-fixtures  # install the locally cloned repo as a package into the venv (to get the latest code)
```

Thank you!

**Comment by dehy** [comment]
It works! Thank you :)
